import {
  getBasicInformation,
  getCharacterStat,
  getHyperStat,
  getAbility,
  getItemEquipment,
  getDojang,
  getCharacterPopularity,
  getPropensity,
  getSetEffect,
  getUnion,
  getSymbolEquipment,
  getSkill,
  getCashItemEquipment,
  getPetEquipment,
  getAndroidEquipment,
  getLinkSkill,
  getVMatrix,
  getHexaMatrix,
  getHexaMatrixStat,

} from '../../api/api';

const apiFunctions = [
  getBasicInformation,
  getCharacterStat,
  getHyperStat,
  getAbility,
  getItemEquipment,
  getDojang,
  getCharacterPopularity,
  getPropensity,
  getSetEffect,
  getUnion,
  getSymbolEquipment,
  getSkill,
  getCashItemEquipment,
  getPetEquipment,
  getAndroidEquipment,
  getLinkSkill,
  getVMatrix,
  getHexaMatrix,
  getHexaMatrixStat,
];

export default apiFunctions;