const hexaStatData = [
  { level: 1, main_stat_name: '공격력 증가', main_stat_level: 5 },
  { level: 2, main_stat_name: '공격력 증가', main_stat_level: 10 },
  { level: 3, main_stat_name: '공격력 증가', main_stat_level: 15 },
  { level: 4, main_stat_name: '공격력 증가', main_stat_level: 20 },
  { level: 5, main_stat_name: '공격력 증가', main_stat_level: 30 },
  { level: 6, main_stat_name: '공격력 증가', main_stat_level: 40 },
  { level: 7, main_stat_name: '공격력 증가', main_stat_level: 50 },
  { level: 8, main_stat_name: '공격력 증가', main_stat_level: 65 },
  { level: 9, main_stat_name: '공격력 증가', main_stat_level: 80 },
  { level: 10, main_stat_name: '공격력 증가', main_stat_level: 100 },
    
  { level: 1, main_stat_name: '마력 증가', main_stat_level: 5 },
  { level: 2, main_stat_name: '마력 증가', main_stat_level: 10 },
  { level: 3, main_stat_name: '마력 증가', main_stat_level: 15 },
  { level: 4, main_stat_name: '마력 증가', main_stat_level: 20 },
  { level: 5, main_stat_name: '마력 증가', main_stat_level: 30 },
  { level: 6, main_stat_name: '마력 증가', main_stat_level: 40 },
  { level: 7, main_stat_name: '마력 증가', main_stat_level: 50 },
  { level: 8, main_stat_name: '마력 증가', main_stat_level: 65 },
  { level: 9, main_stat_name: '마력 증가', main_stat_level: 80 },
  { level: 10, main_stat_name: '마력 증가', main_stat_level: 100 },

  { level: 1, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '0.35%' },
  { level: 2, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '0.7%' },
  { level: 3, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '1.05%' },
  { level: 4, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '1.4%' },
  { level: 5, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '2.1%' },
  { level: 6, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '2.8%' },
  { level: 7, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '3.5%' },
  { level: 8, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '4.55%' },
  { level: 9, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '5.6%' },
  { level: 10, main_stat_name: '크리티컬 데미지 증가', main_stat_level: '7%' },

  { level: 1, main_stat_name: '보스 데미지', main_stat_level: '1%' },
  { level: 2, main_stat_name: '보스 데미지', main_stat_level: '2%'},
  { level: 3, main_stat_name: '보스 데미지', main_stat_level: '3%' },
  { level: 4, main_stat_name: '보스 데미지', main_stat_level: '4%' },
  { level: 5, main_stat_name: '보스 데미지', main_stat_level: '6%' },
  { level: 6, main_stat_name: '보스 데미지', main_stat_level: '8%' },
  { level: 7, main_stat_name: '보스 데미지', main_stat_level: '10%' },
  { level: 8, main_stat_name: '보스 데미지', main_stat_level: '13%' },
  { level: 9, main_stat_name: '보스 데미지', main_stat_level: '16%' },
  { level: 10, main_stat_name: '보스 데미지', main_stat_level: '20%' },

  { level: 1, main_stat_name: '방어율 무시', main_stat_level: '1%' },
  { level: 2, main_stat_name: '방어율 무시', main_stat_level: '2%' },
  { level: 3, main_stat_name: '방어율 무시', main_stat_level: '3%' },
  { level: 4, main_stat_name: '방어율 무시', main_stat_level: '4%' },
  { level: 5, main_stat_name: '방어율 무시', main_stat_level: '6%' },
  { level: 6, main_stat_name: '방어율 무시', main_stat_level: '8%' },
  { level: 7, main_stat_name: '방어율 무시', main_stat_level: '10%' },
  { level: 8, main_stat_name: '방어율 무시', main_stat_level: '13%' },
  { level: 9, main_stat_name: '방어율 무시', main_stat_level: '16%' },
  { level: 10, main_stat_name: '방어율 무시', main_stat_level: '20%' },

  { level: 1, main_stat_name: '데미지', main_stat_level: '0.75%' },
  { level: 2, main_stat_name: '데미지', main_stat_level: '1.5%' },
  { level: 3, main_stat_name: '데미지', main_stat_level: '2.25%' },
  { level: 4, main_stat_name: '데미지', main_stat_level: '3%' },
  { level: 5, main_stat_name: '데미지', main_stat_level: '4.5%' },
  { level: 6, main_stat_name: '데미지', main_stat_level: '6%' },
  { level: 7, main_stat_name: '데미지', main_stat_level: '7.5%' },
  { level: 8, main_stat_name: '데미지', main_stat_level: '9.75%' },
  { level: 9, main_stat_name: '데미지', main_stat_level: '12%' },
  { level: 10, main_stat_name: '데미지', main_stat_level: '15%' },


  { level: 1, main_stat_name: '주스탯 증가', main_stat_level: [100, 48, 2100] },
  { level: 2, main_stat_name: '주스탯 증가', main_stat_level: [200, 96, 4200] },
  { level: 3, main_stat_name: '주스탯 증가', main_stat_level: [300, 144, 6300] },
  { level: 4, main_stat_name: '주스탯 증가', main_stat_level: [400, 192, 8400] },
  { level: 5, main_stat_name: '주스탯 증가', main_stat_level: [600, 288, 12600] },
  { level: 6, main_stat_name: '주스탯 증가', main_stat_level: [800, 384, 16800] },
  { level: 7, main_stat_name: '주스탯 증가', main_stat_level: [1000, 480, 21000] },
  { level: 8, main_stat_name: '주스탯 증가', main_stat_level: [1300, 624, 27300] },
  { level: 9, main_stat_name: '주스탯 증가', main_stat_level: [1600, 768, 33600] },
  { level: 10, main_stat_name: '주스탯 증가', main_stat_level: [2000, 960, 42000] },

];


export default hexaStatData;