const dummyUserData = {
  getCombinedData: {
    getBasicInformation: {
      date: null,
      character_name: "메짱",
      world_name: "메짱",
      character_gender: "여",
      character_class: "나이트워커",
      character_class_level: "6",
      character_level: 287,
      character_exp: 123111,
      character_exp_rate: "7.638",
      character_guild_name: "메짱",
      character_image: "-",
      character_date_create: "2022-04-11T00:00+09:00",
      access_flag: "true",
      liberation_quest_clear: "1",
    },
    getCharacterPopularity: {
      date: null,
      popularity: 72,
    },
    getCharacterStat: {
      date: null,
      character_class: "나이트워커",
      final_stat: [
        { stat_name: "최소 스탯공격력", stat_value: "71043262" },
        { stat_name: "최대 스탯공격력", stat_value: "83580307" },
        { stat_name: "데미지", stat_value: "91.00" },
        { stat_name: "보스 몬스터 데미지", stat_value: "481.00" },
        { stat_name: "최종 데미지", stat_value: "66.98" },
        { stat_name: "방어율 무시", stat_value: "93.59" },
        { stat_name: "크리티컬 확률", stat_value: "90" },
        { stat_name: "크리티컬 데미지", stat_value: "107.75" },
        { stat_name: "상태이상 내성", stat_value: "75" },
        { stat_name: "스탠스", stat_value: "100" },
        { stat_name: "방어력", stat_value: "56630" },
        { stat_name: "이동속도", stat_value: "170" },
        { stat_name: "점프력", stat_value: "123" },
        { stat_name: "스타포스", stat_value: "323" },
        { stat_name: "아케인포스", stat_value: "1410" },
        { stat_name: "어센틱포스", stat_value: "500" },
        { stat_name: "STR", stat_value: "5785" },
        { stat_name: "DEX", stat_value: "12808" },
        { stat_name: "INT", stat_value: "6160" },
        { stat_name: "LUK", stat_value: "67603" },
        { stat_name: "HP", stat_value: "58023" },
        { stat_name: "MP", stat_value: "30554" },
        { stat_name: "AP 배분 STR", stat_value: "4" },
        { stat_name: "AP 배분 DEX", stat_value: "4" },
        { stat_name: "AP 배분 INT", stat_value: "4" },
        { stat_name: "AP 배분 LUK", stat_value: "1453" },
        { stat_name: "AP 배분 HP", stat_value: "0" },
        { stat_name: "AP 배분 MP", stat_value: "0" },
        { stat_name: "아이템 드롭률", stat_value: "12" },
        { stat_name: "메소 획득량", stat_value: "4" },
        { stat_name: "버프 지속시간", stat_value: "50" },
        { stat_name: "공격 속도", stat_value: "6" },
        { stat_name: "일반 몬스터 데미지", stat_value: "32.00" },
        { stat_name: "재사용 대기시간 감소 (초)", stat_value: "2" },
        { stat_name: "재사용 대기시간 감소 (%)", stat_value: "6" },
        { stat_name: "재사용 대기시간 미적용", stat_value: "6" },
        { stat_name: "속성 내성 무시", stat_value: "5.00" },
        { stat_name: "상태이상 추가 데미지", stat_value: "13.00" },
        { stat_name: "무기 숙련도", stat_value: "85" },
        { stat_name: "추가 경험치 획득", stat_value: "60.00" },
        { stat_name: "공격력", stat_value: "5722" },
        { stat_name: "마력", stat_value: "1167" },
        { stat_name: "전투력", stat_value: "294669443" },
        { stat_name: "소환수 지속시간 증가", stat_value: "10" },
      ],
      remain_ap: 0,
    },
    getPropensity: {
      date: null,
      charisma_level: 100,
      sensibility_level: 100,
      insight_level: 100,
      willingness_level: 100,
      handicraft_level: 100,
      charm_level: 100,
    },
    getAbility: {
      date: null,
      ability_grade: "레전드리",
      ability_info: [
        {
          ability_no: "1",
          ability_grade: "레전드리",
          ability_value: "보스 몬스터 공격 시 데미지 19% 증가",
        },
        {
          ability_no: "2",
          ability_grade: "유니크",
          ability_value: "공격력 21 증가",
        },
        {
          ability_no: "3",
          ability_grade: "유니크",
          ability_value: "상태 이상에 걸린 대상 공격 시 데미지 7% 증가",
        },
      ],
      remain_fame: 522507,
      preset_no: 2,
      ability_preset_1: {
        ability_preset_grade: "레전드리",
        ability_info: [
          {
            ability_no: "1",
            ability_grade: "레전드리",
            ability_value: "DEX 37 증가, STR 19 증가",
          },
          {
            ability_no: "2",
            ability_grade: "유니크",
            ability_value: "상태 이상에 걸린 대상 공격 시 데미지 7% 증가",
          },
          {
            ability_no: "3",
            ability_grade: "유니크",
            ability_value: "아이템 드롭률 15% 증가",
          },
        ],
      },
      ability_preset_2: {
        ability_preset_grade: "레전드리",
        ability_info: [
          {
            ability_no: "1",
            ability_grade: "레전드리",
            ability_value: "보스 몬스터 공격 시 데미지 19% 증가",
          },
          {
            ability_no: "2",
            ability_grade: "유니크",
            ability_value: "공격력 21 증가",
          },
          {
            ability_no: "3",
            ability_grade: "유니크",
            ability_value: "상태 이상에 걸린 대상 공격 시 데미지 7% 증가",
          },
        ],
      },
      ability_preset_3: {
        ability_preset_grade: "레전드리",
        ability_info: [
          {
            ability_no: "1",
            ability_grade: "레전드리",
            ability_value: "아이템 드롭률 19% 증가",
          },
          {
            ability_no: "2",
            ability_grade: "유니크",
            ability_value: "메소 획득량 14% 증가",
          },
          {
            ability_no: "3",
            ability_grade: "에픽",
            ability_value: "상태 이상에 걸린 대상 공격 시 데미지 4% 증가",
          },
        ],
      },
    },
    getHyperStat: {
      hyper_stat_preset_1: [
        { stat_type: "STR", stat_level: 0, stat_increase: "STR +0" },
        { stat_type: "DEX", stat_level: 0, stat_increase: "DEX +0" },
        { stat_type: "INT", stat_level: 0, stat_increase: "INT +0" },
        { stat_type: "LUK", stat_level: 5, stat_increase: "LUK +75" },
        { stat_type: "HP", stat_level: 0, stat_increase: "HP +0" },
        { stat_type: "MP", stat_level: 0, stat_increase: "MP +0" },
        { stat_type: "DF/TF", stat_level: 0, stat_increase: "DF/TF +0" },
        {
          stat_type: "크리티컬 확률",
          stat_level: 7,
          stat_increase: "크리티컬 확률 +21%",
        },
        {
          stat_type: "크리티컬 데미지",
          stat_level: 13,
          stat_increase: "크리티컬 데미지 +12%",
        },
        {
          stat_type: "방어율 무시",
          stat_level: 12,
          stat_increase: "방어율 무시 +30%",
        },
        { stat_type: "데미지", stat_level: 12, stat_increase: "데미지 +24%" },
        {
          stat_type: "보스 몬스터 데미지",
          stat_level: 0,
          stat_increase: "보스 몬스터 데미지 +0%",
        },
        {
          stat_type: "상태 이상 내성",
          stat_level: 0,
          stat_increase: "상태 이상 내성 +0",
        },
        {
          stat_type: "공격력/마력",
          stat_level: 5,
          stat_increase: "공격력/마력 +15",
        },
        {
          stat_type: "획득 경험치",
          stat_level: 8,
          stat_increase: "획득 경험치 +4%",
        },
        {
          stat_type: "아케인포스",
          stat_level: 0,
          stat_increase: "아케인포스 +0",
        },
        {
          stat_type: "일반 몬스터 공격 시 데미지 증가",
          stat_level: 13,
          stat_increase: "일반 몬스터 공격 시 데미지 +39%",
        },
      ],
      hyper_stat_preset_1_remain_point: 51,
      hyper_stat_preset_2: [],
      hyper_stat_preset_2_remain_point: 51,
      hyper_stat_preset_3: [],
      hyper_stat_preset_3_remain_point: 51,
    },
    getDojang: { dojang_best_floor: 55 },
    getUnion: { union_level: 9267 },
  },
  getExpHistory: [
    {
      date: "2025-12-30",
      character_exp: 9196667825161,
      character_exp_rate: "7.638",
    },
    {
      date: "2025-12-29",
      character_exp: 9196667825161,
      character_exp_rate: "7.638",
    },
    {
      date: "2025-12-28",
      character_exp: 8985387720500,
      character_exp_rate: "7.462",
    },
    {
      date: "2025-12-27",
      character_exp: 4646979398911,
      character_exp_rate: "3.859",
    },
    {
      date: "2025-12-26",
      character_exp: 4646979398911,
      character_exp_rate: "3.859",
    },
    {
      date: "2025-12-25",
      character_exp: 4002814927375,
      character_exp_rate: "3.324",
    },
    {
      date: "2025-12-24",
      character_exp: 3726890227371,
      character_exp_rate: "3.095",
    },
    {
      date: "2025-12-23",
      character_exp: 3605469979058,
      character_exp_rate: "2.994",
    },
    {
      date: "2025-12-22",
      character_exp: 3605469979058,
      character_exp_rate: "2.994",
    },
    {
      date: "2025-12-21",
      character_exp: 103013228704860,
      character_exp_rate: "94.107",
    },
    {
      date: "2025-12-20",
      character_exp: 103013228704860,
      character_exp_rate: "94.107",
    },
    {
      date: "2025-12-19",
      character_exp: 103013228704860,
      character_exp_rate: "94.107",
    },
    {
      date: "2025-12-18",
      character_exp: 103013085204311,
      character_exp_rate: "94.107",
    },
    {
      date: "2025-12-17",
      character_exp: 102573654267057,
      character_exp_rate: "93.706",
    },
  ],
};

export default dummyUserData;
