name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때 실행


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        run: |
          scp -r . ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/maple
          

      - name: Run deploy script
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} 'chmod +x /home/ubuntu/maple/deploy.sh'

          