name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to EC2 using rsync
        run: |
          rsync -avz --exclude '.git' --exclude 'node_modules' --exclude 'logs' \
          -e "ssh -i ~/.ssh/id_rsa" . ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/maple

      - name: Run deploy script
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} 'bash /home/ubuntu/maple/deploy.sh'
